### ISSUE TITLE
Pagination - Fix peer dependency for framer-motion

### ISSUE THREAD

**Issue by SheaBelsky** [niconiahi/ajna#11]
On Node 16, `npm install` fails in a project where this package is installed because the peer dependency `framer-motion` is listed as `^3 || ^4`, meanwhile the primary `@chakra-ui/react` package explicitly depends on `^5`. 

https://github.com/niconiahi/ajna/blob/51cd64b7e013dcd9cbe3c71288caf85b6c0d7ff8/packages/pagination/package.json#L43

Is it possible to fix this? Is this as simple as just updating the peer dependency to `^5 || ^6`? If so, I can put up a pull request to do that.

**Comment by niconiahi** [comment]
I think it should be fixed now. This was it!
