### ISSUE TITLE
Chakra paginator + Next.js memory leak

### ISSUE THREAD

**Issue by HonzaVrkota** [niconiahi/ajna#3]
### Error description
In my Next.js i use Chakra UI and Chakra Paginator.
On page when I use Paginator and Chakra Toast - toast doesnt work.
In console it show error:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
ToastManager@http://localhost:3000/_next/static/chunks/pages/_app.js?ts=1627303273546:38352:5`
When I delete all chakra-paginator components and hooks, Toasts works. This is how I realised the error is coused by chakra-paginator. 

Do you have any advice how to repair and make it works with Next.js and Chakra Toasts?

**Comment by makstr** [comment]
Getting exactly the same error with toast on nextjs
