### ISSUE TITLE
[BUG] - Cannot import library, get "Module not found" error

### ISSUE THREAD

**Issue by fP4rad0x** [niconiahi/ajna#4]
Hello, so, I'm getting this "Module not found" error whenever I try to import and use your library.
I just copy-pasted the example on CodeSandbox: https://codesandbox.io/s/ajna-pagination-forked-0i2i1?file=/src/App.tsx
Tried with both normal javascript and typescript, neither works.

Kudos for your hard work btw. The snippet in CodeSandbox is amazing!

![image](https://user-images.githubusercontent.com/37763819/128395584-426f6cfa-8ec1-4ed4-a3ee-9c67f8a08529.png)

**Comment by brayanarrieta** [comment]
I'm having the same issue any idea of how to fix

**Comment by jarvissa** [comment]
Same here

**Comment by niconiahi** [comment]
Hey guys! thank you for rising it. It's fixed now. I hope you can enjoy it now. 
Would love to hear feedback if you ever want to, thanks!

**Comment by houssem-yahiaoui** [comment]
@niconiahi its seems we're having the same issue on this again, can you please help us

**Comment by kfancy** [comment]
Confirmed, `dist` folder is not included in the installed package.
