### ISSUE TITLE
Update Paginator react-scripts dependency

### ISSUE THREAD

**Issue by enmielado** [niconiahi/ajna#8]
Thank you for this package. It's working nicely on our site.

Would it be possible to update the react-scripts dependency to a current version? The old version of react-scripts has dependencies that cause many npm security vulnerability warnings.

Using: node 16.13 and npm 8.1

Update: updating framer-motion would also be helpful

**Comment by niconiahi** [comment]
hi! yes sure. I'll give the dependencies a bump one of these days. Expect it to be ready before next Friday. Thanks for flagging and the compliment

**Comment by enmielado** [comment]
@niconiahi Thanks for addressing this. I'm still seeing security warnings regarding react-scripts though. Perhaps because the react-scripts version was updated in devDependencies but not peerDependencies??

**Comment by niconiahi** [comment]
this is updated on version `1.4.9`
